vim.keymap.set("n", "<leader>tf", function()
  require("mini.test").run_file()
end)
vim.keymap.set("n", "<leader>ta", function()
  require("mini.test").run()
end)

vim.keymap.set("n", "<leader>td", function()
  require("mini.doc").generate()
end)
